import turtle
wn = turtle.Screen()
wn.bgcolor("brown")
tess = turtle.Turtle()
tess.shape("turtle")
tess.color("yellow")

tess.left(90)
tess.forward(50)          
tess.right(135)             
tess.forward(65)
tess.left(135)
tess.forward(50)  
tess.penup()

tess.right(90)   
tess.forward(100)       
tess.pendown()
tess.right(180)       
tess.forward(40)    
tess.left(90)       
tess.forward(50)
tess.left(90)       
tess.forward(50)
tess.left(90)       
tess.forward(25)       
tess.left(90)       
tess.forward(25)       

wn.mainloop()